### ISSUE TITLE
是否能提供下测试数据集呢？

### ISSUE THREAD

**Issue by ccfendouing** [ZhiChen902/SC2-PCR#11]
我在我的机子上测试出来pointDSC和你的SC2-PCR 发现结果和论文有比较大差距，并且我实验了下发现利用PointDSC的描述符去补足 空间一致性 导致了更差的结果，不知道您在做实验的时候有没有发现这一点

**Comment by ZhiChen902** [comment]
我做实验暂时没有发现这个问题。3DMatch的测试数据集PointDSC有提供，KITTI的测试数据集我们提供在这个链接：https://drive.google.com/drive/folders/1sxkHYjWHhSUE3IcvmZ2p1ziw1LqJqqfc

**Comment by ZhiChen902** [comment]
我本来想开源一下3DMatch的FCGF和FPFH描述子，但是我的谷歌网盘不够用了。PointDSC提供了生成描述子的代码，您可以参考一下，链接为：https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fcgf.py 和 https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fpfh.py. 生成匹配对用描述子空间的近邻查找即可，在SC2-PCR的代码中有。

**Comment by Theigrams** [comment]
> 我本来想开源一下3DMatch的FCGF和FPFH描述子，但是我的谷歌网盘不够用了。PointDSC提供了生成描述子的代码，您可以参考一下，链接为：https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fcgf.py 和 https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fpfh.py. 生成匹配对用描述子空间的近邻查找即可，在SC2-PCR的代码中有。

您好，关于3DMatch的FCGF和FPFH描述子，请问可否提供百度网盘的下载链接呢？
