### ISSUE TITLE
关于关键点和描述子的提取

### ISSUE THREAD

**Issue by Xinyi-tum** [ZhiChen902/SC2-PCR#13]
非常感谢您的开源代码！！我有几个细节的小问题想请教一下

1）您提供了KITTI数据集的FCGF描述子的下载，想请问下每一个点云对的8000对关键点您是随机采样的吗？
2）您的代码中本部分计算correspondence是指在all-to-all的情况下寻找每个点的一个最近邻点吗，也就是关键点的数量=correspondence的数量？
![image](https://user-images.githubusercontent.com/61148982/210530291-e7b9db46-d8ff-4b75-b35b-c158637f16d8.png)

3）如下，您提供的KITTI配置文件中，"num_node": 8000和"max_points": 8000分别是指什么意思呢？哪个值对应提取的关键点数或者是correspondence数量呢？
{
    "CUDA_Devices": "1",
    "num_iterations": 20,
    "dataset": "KITTI",
    "ratio": 0.2,
    "k1": 30,
    "k2": 20,
    "data_path": "data/KITTI/fpfh_test",
    "descriptor": "fpfh",
    "inlier_threshold": 0.6,
    "d_thre": 0.1,
    "downsample": 0.3,
    "re_thre": 5,
    "te_thre": 60,
    "num_node": 8000,
    "use_mutual": false,
    "max_points": 8000,
    "nms_radius": 0.6
}

**Comment by ZhiChen902** [comment]
1、是的，目前我在KITTI数据集的8000关键点是随机采样的。如果这个描述子提供了关键点的其他信息，比如显著性得分和重叠区域得分，也可以根据其他信息采样；
2、是的，我在计算correspondences的时候是在all-to-all的情况下为每个源点云找一个最近邻点。我也尝试过利用比如互为最近邻的策略去查找correspondences,但是结果不如直接all-to-all查找。
3、num_node是用来选择保留所有点还是随机采样固定点的参数。max_point只是一个保护，比如你选择了保留所有correspondences，但是对于某一对点云来说，保留所有的correspondences的数量可能很大，这个时候max_point会截取一部分点来进行计算，防止内存溢出。

**Comment by Xinyi-tum** [comment]
非常感谢您的回复！！我还有几个进一步的问题：
1) 8000这个correspondence的数量应该非常影响算法的速度，但是您的论文中没有提到8000这个数字，请问这是默认值吗？我在PointDsc的论文中也没有找到这个描述（但是它在KITTI数据集的correspondence应该设置的是12000），以及根据您的配置文件，KITTI数据集和3DMatch数据集您都设置的8000，而3DLOMatch数据集是5000，我想了解下这个数量是怎么设置的

2) PointDsc中提供的3DMatch数据集的FCGF和FPFH描述子的下载链接已经失效了，我想了解下其中每一帧点云的关键点和描述子的数量，请问是5000吗还是跟您一样是8000？因为他们的代码中是num_node='all'

**Comment by ZhiChen902** [comment]
感谢您的关注。
1、计算二阶相似性时需要将两个矩阵进行相乘，因此如果匹配对数量过多会导致通常使用的12G显存显卡显存溢出。我们设置8000个点正是防止这个问题。我们考虑点越少应该估计难度越大，我们用的点没有比其他方法多，所以我们和其他方法的性能对比应该是公平的。至于速度，这个确实有一点影响，这也是我们可能有点疏忽的地方，但是我觉得应该影响不太大。3DMatch数据集经过5cm voxel降采样后大部分匹配对都少于8000对，所以这个保护应该是没有执行的。KITTI数据集经过降采样后有些匹配确实会大于8000，如果不利用8000点截取应该速度会稍微慢一点。至于3DLoMatch，我们是遵循原文Predator的设置。Predator采用采样固定匹配对的方法，最多采样5000个匹配对。为了公平的对比其他方法，我们对所有的方法都只采用了5000对匹配对。

2、PointDsc中提供的3DMatch数据集的FCGF和FPFH描述子的下载链接确实失效了。我们本质上和PointDSC的设置一样，对于3DMatch和KITTI数据集来说，我们都是期望利用“all”，即所有可能的匹配对，但是当匹配对数量大于8000时，我们只用8000对，这是一个显存保护。至于3DLoMatch，我们在做实验时遵循Predator的设置，对所有的方法都采用5000对匹配对。

3、我本来想开源一下3DMatch的FCGF和FPFH描述子，但是我的谷歌网盘不够用了。PointDSC提供了生成描述子的代码，链接为：https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fcgf.py 和 https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fpfh.py. 生成匹配对用描述子空间的近邻查找即可，在SC2-PCR的代码中有。

**Comment by ZhiChen902** [comment]
感谢您的关注。
1、计算二阶相似性时需要将两个矩阵进行相乘，因此如果匹配对数量过多会导致通常使用的12G显存显卡显存溢出。我们设置8000个点正是防止这个问题。我们考虑点越少应该估计难度越大，我们用的点没有比其他方法多，所以我们和其他方法的性能对比应该是公平的。至于速度，这个确实有一点影响，这也是我们可能有点疏忽的地方，但是我觉得应该影响不太大。3DMatch数据集经过5cm voxel降采样后大部分匹配对都少于8000对，所以这个保护应该是没有执行的。KITTI数据集经过降采样后有些匹配确实会大于8000，如果不利用8000点截取应该速度会稍微慢一点。至于3DLoMatch，我们是遵循原文Predator的设置。Predator采用采样固定匹配对的方法，最多采样5000个匹配对。为了公平的对比其他方法，我们对所有的方法都只采用了5000对匹配对。

2、PointDsc中提供的3DMatch数据集的FCGF和FPFH描述子的下载链接确实失效了。我们本质上和PointDSC的设置一样，对于3DMatch和KITTI数据集来说，我们都是期望利用“all”，即所有可能的匹配对，但是当匹配对数量大于8000时，我们只用8000对，这是一个显存保护。至于3DLoMatch，我们在做实验时遵循Predator的设置，对所有的方法都采用5000对匹配对。

3、我本来想开源一下3DMatch的FCGF和FPFH描述子，但是我的谷歌网盘不够用了。PointDSC提供了生成描述子的代码，您可以参考一下，链接为：https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fcgf.py 和 https://github.com/XuyangBai/PointDSC/blob/master/misc/cal_fpfh.py. 生成匹配对用描述子空间的近邻查找即可，在SC2-PCR的代码中有。

**Comment by Xinyi-tum** [comment]
不好意思，回复迟了，还有个小问题想跟您请教一下

我理解的关于建立correspondence的整体思路是，对于点云第一步随机采样关键点，然后根据描述子特征在特征空间中计算all-to-all的距离，对源点云中的每一个关键点选取一个最近的目标点云中的点建立correspondence，这样的话，关键点的数量=correspondence的数量，这样理解对吗？以及PointDsc中生成correspondence也是这个策略吧？不过根据我的了解，找最近点的时候应当有个最低的阈值或者条件，生成的correspondence的数量应当小于关键点的数量，这样好像更合理一些（correspondence中的内点率会变高，同时correspondence的数量也会变小，这样的输入更加有利于配准算法）？

**Comment by ZhiChen902** [comment]
是的，您说的这种最低阈值过滤tiaojian

**Comment by ZhiChen902** [comment]
是的，您说的这种阈值过滤是一种很常见的做法，比如互为最近邻，还有二维匹配中常用的Lowe比（二近邻和最近邻描述子距离的比值）。这种策略可以提高内点率，但是也会造成一些潜在的正确匹配被这种策略过滤了。我们尝试过互为最近邻策略，发现结果不如直接保留所有匹配对。可能有其他更合理的策略，但是我们没有进一步探索这个匹配策略的影响。
