### ISSUE TITLE
how to run it on Windows OS

### ISSUE THREAD

**Issue by Liuyveg** [ZhiChen902/SC2-PCR#14]

**Comment by ZhiChen902** [comment]
Thank you for your attention.
I notice that there is someone who achieved SC2-PCR in C++: https://github.com/smalltheater/SC2-PCR and https://github.com/mujiubai/SC2-PCR-CPP. I didn't test the code. Maybe you can try.

**Comment by Liuyveg** [comment]
OK, thanks for your reply.
