### ISSUE TITLE
3DMatch FPFH描述子测试结果

### ISSUE THREAD

**Issue by jianganghuang** [ZhiChen902/SC2-PCR#15]
1. 你好，非常感谢您优秀的工作。在测试3DMatch FPFH描述子时遇到一点问题，六个指标（RR,RE,TE,IP,IR,F1）中前三个指标比论文中的数据略差，后三个指标比论文中数据略好，未更改代码，截图如下

![image](https://user-images.githubusercontent.com/127812522/224881685-dcdfd3d6-0b8b-43d0-9fbf-9734363065e4.png)
我跑出来的测试结果
![image](https://user-images.githubusercontent.com/127812522/224881885-68c9db4a-14c9-4333-a7c1-b4c227dba93c.png)

正常来讲，这六个指标不应该同时变好或者同时变坏的吗？，我主要关注前三个指标，尤其是RR，想请教下您是如何得到论文中的结果的，需要调整哪些参数

2，另外，对内点率这个概念有些疑问，我注意到KITTI FCGF描述子的内点率是30%+，而KITTI FPFH描述子的内点率只有3%+，FCGF描述子和FPFH描述子对应的点云对难道不是一样的吗，如果一样这两个描述子的内点率为什么会不一样

**Comment by jianganghuang** [comment]
不好意思描述有错，是RR和TE指标变差，RE和后三个指标变好

**Comment by ZhiChen902** [comment]
您好，感谢您的关注。

我们在代码优化的时候可能会导致性能与论文中有些许差异。至于指标的好坏，它们并不是同时变好变坏的。这与我们通常采用的评测方式有关。在计算RE和TE时，为了排除某些极端值对平均结果的影响，我们只会计算RR=1的那些点云对的平均误差。这样，如果RR越高时，计算平均RE和TE时考虑的的点云对越多，这可能导致计算出来的RE和TE越高。

对于内点率，这个是和描述子相关的。内点率表示的是用不同的描述子建立的匹配中正确匹配的比例，不同描述子建立的匹配是不同的，因此内点率也是不同的。
