### ISSUE TITLE
SC2计算相关问题

### ISSUE THREAD

**Issue by neverCV** [ZhiChen902/SC2-PCR#16]
您好，非常感谢您的工作，它十分的优秀。在研究您的代码的过程中我发现SC2矩阵计算的过程中使用了两个不同阈值的 SC矩阵，一个是d_thre另一个是d_thre/2。请问这里有什么说法嘛。

**Comment by ZhiChen902** [comment]
感谢您的关注。
SC2 可以被表达为SC * (SC × SC), *为矩阵逐像素相乘，而×为矩阵乘法，这其中涉及三个SC矩阵。在计算第一个SC矩阵时，我们使用的阈值为d_thre，而在计算第二个和第三个SC矩阵时，我们使用的阈值为d_thre/2。我们选择这么做的原因是因为这三个矩阵有不同的作用。我们对第二和第三个SC矩阵进行矩阵乘法，是为了统计每两个匹配的共同兼容性匹配的个数，这里的阈值设置得小一点是为了减少在统计时的噪声。而第一个SC是判断两个匹配点本身是不是兼容的，如果它们本身不兼容，那么我们认为它们的二阶兼容性为0。这里阈值稍微设置大一点是防止有些匹配本身兼容的点之间的兼容性被置0
