### ISSUE TITLE
关于调参

### ISSUE THREAD

**Issue by fuzhao123232** [ZhiChen902/SC2-PCR#18]
![image](https://github.com/ZhiChen902/SC2-PCR/assets/115547529/1002d453-b240-4226-9309-5545beeba0d3)
请问作者，我直接使用默认参数后的效果很差，是和参数有关吗

**Comment by ZhiChen902** [comment]
我觉得可以从两个方面排查一下问题：1）不知道您用的是什么描述子建立匹配，如果建立的初始匹配过于差，可能导致匹配效果不好。2）有些参数可能需要根据voxel size进行调整，最可能影响结果的参数是config文件中的d_thre，需要根据voxel size进行设置，可以尝试设置为voxel size的1到2倍之间。

**Comment by fuzhao123232** [comment]
![image](https://github.com/ZhiChen902/SC2-PCR/assets/115547529/ad810511-e9ac-4540-8cba-8639298a3310)
请问作者，我现在可以配了，但是配歪了，这种情况是为什么啊？
