### ISSUE TITLE
Combined with pointDSC

### ISSUE THREAD

**Issue by smalltheater** [ZhiChen902/SC2-PCR#6]
How to utilize SC^2 to improve the performance of pointDSC?  Did you use the SC2_measure from : https://github.com/ZhiChen902/SC2-PCR/blob/e1994d8e87d51412f1cf7c88f4e4511a4a31597a/SC2_PCR.py#L353

and replace the normed_corr_features with SC^2 in : 

https://github.com/XuyangBai/PointDSC/blob/b009d536ac10b570853833f2178397c154745da9/models/PointDSC.py#L182

**Comment by ZhiChen902** [comment]
Yes.
