### ISSUE TITLE
can you expalin the result of DHVR in Tab1?

### ISSUE THREAD

**Issue by ccfendouing** [ZhiChen902/SC2-PCR#7]
DHVR has not released the code, how did you measure his result?
original words from your paper:The results of DHVR we tested have some difference with the original results, so we also report the results in their paper (DHVR-Origin in Tab. 1).

**Comment by ZhiChen902** [comment]
The code of DHVR is available here: https://github.com/POSTECH-CVLab/DHVR

**Comment by ccfendouing** [comment]
thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月30日(星期天) 晚上11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhiChen902/SC2-PCR] can you expalin the result of DHVR in Tab1? (Issue #7)





 
The code of DHVR is available here: https://github.com/POSTECH-CVLab/DHVR
