### ISSUE TITLE
与SAC-COT相比？

### ISSUE THREAD

**Issue by PANFEI-CHENG** [ZhiChen902/SC2-PCR#8]
我觉得您的论文和SAC-COT在思想上有一定的相似性，请问作者您和SAC-COT: Sample Consensus by Sampling Compatibility Triangles in Graphs for 3-D Point Cloud Registration这篇论文有进行过比较么？

**Comment by ZhiChen902** [comment]
是的，我们的方法与SAC-COT都是为了减轻空间兼容性的ambiguity带来的问题。我们没有与SAC-COT对比，因为SAC-COT并没有开源，且原文中也没有放出我们论文中所用的数据集的结果。由于SAC-COT涉及的细节比较多，我们也没有尝试去复现它

**Comment by PANFEI-CHENG** [comment]
本来我也以为没有开源，但其实开源了的，应该是两年以前，在github搜的到，只不过点进去后要选择master那个页面。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月1日(周二) 凌晨0:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZhiChen902/SC2-PCR] 与SAC-COT相比？ (Issue #8)




 
是的，我们的方法与SAC-COT都是为了减轻空间兼容性的ambiguity带来的问题。我们没有与SAC-COT对比，因为SAC-COT并没有开源，且原文中也没有放出我们论文中所用的数据集的结果。由于SAC-COT涉及的细节比较多，我们也没有尝试去复现它

**Comment by PANFEI-CHENG** [comment]
https://github.com/ytuhzq/SAC-COT/tree/master



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月1日(周二) 凌晨0:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZhiChen902/SC2-PCR] 与SAC-COT相比？ (Issue #8)




 
是的，我们的方法与SAC-COT都是为了减轻空间兼容性的ambiguity带来的问题。我们没有与SAC-COT对比，因为SAC-COT并没有开源，且原文中也没有放出我们论文中所用的数据集的结果。由于SAC-COT涉及的细节比较多，我们也没有尝试去复现它

**Comment by ZhiChen902** [comment]
好的，感谢您的分享
