### ISSUE TITLE
How to add the method  into the PointDsc？

### ISSUE THREAD

**Issue by hongsir123** [ZhiChen902/SC2-PCR#9]

**Comment by ZhiChen902** [comment]
As described in our paper: "Instead of retraining the network, we directly plugged our metrics into it", i.e., we replace the normed_corr_features with SC^2.

**Comment by hongsir123** [comment]
So you didn't use SCNonlocal to combined with the input feature map,but the function self.cal_seed_trans in https://github.com/XuyangBai/PointDSC/blob/b009d536ac10b570853833f2178397c154745da9/models/PointDSC.py#L182
don't need to change it?

**Comment by hongsir123** [comment]
Can you provide the PointDSC  code combined with your method

**Comment by ZhiChen902** [comment]
In PointDSC, the similarity between two correspondences is computed by feature similarity. We replace the way of computing feature similarity with the SC^2 measure, and don't change other part.

**Comment by hongsir123** [comment]
So you're not using features and spatial features aren't fed into the next network?
https://github.com/XuyangBai/PointDSC/blob/b009d536ac10b570853833f2178397c154745da9/models/PointDSC.py#L155
if SC2 directly used in this self.cal_seed_trans function. However, the PointDSC core is on the SCNonlocal network, so the comparison is not very meaningful after this modification?

**Comment by ZhiChen902** [comment]
We didn't try to retrain the network as we don't have the training dataset of PointDSC.  We think that since SC^2 can improve the performance of PointDSC without training, then if training optimization is used, the performance will be further improved. At least it won't get worse.
